### ISSUE TITLE
Build fails with --os linux-x86_64-gpu option

### ISSUE THREAD

**Issue by kmotohas** [KonduitAI/konduit-serving#115]
I'm in a machine of Ubuntu16.04 with CUDA 10.1.
`konduit init --os linux-86_64-gpu` fails and shows the following error messages.

```
...
Downloading from maven-restlet: http://maven.restlet.org/org/bytedeco/leptonica/1.78.0-1.5.1/leptonica-1.78.0-1.5.1-linux-x86_64-gpu.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for konduit-serving 1.2.1:
[INFO] 
[INFO] konduit-serving .................................... SUCCESS [  0.797 s]
[INFO] konduit-serving-api ................................ FAILURE [ 14.993 s]
[INFO] konduit-serving-core ............................... SKIPPED
[INFO] konduit-serving-codegen ............................ SKIPPED
[INFO] konduit-serving-pmml ............................... SKIPPED
[INFO] konduit-serving-gpu ................................ SKIPPED
[INFO] konduit-serving-python ............................. SKIPPED
[INFO] konduit-serving-distro-bom ......................... SKIPPED
[INFO] konduit-serving-orchestration ...................... SKIPPED
[INFO] konduit-serving-uberjar ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17.086 s
[INFO] Finished at: 2019-12-03T10:57:26+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project konduit-serving-api: Could not resolve dependencies for project ai.konduit.serving:konduit-serving-api:jar:1.2.1: The following artifacts could not be resolved: org.bytedeco:hdf5:jar:linux-x86_64-gpu:1.10.5-1.5.1, org.bytedeco:leptonica:jar:linux-x86_64-gpu:1.78.0-1.5.1: Could not find artifact org.bytedeco:hdf5:jar:linux-x86_64-gpu:1.10.5-1.5.1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :konduit-serving-api
Traceback (most recent call last):
  File "/home/ubuntu/.konduit/konduit-serving/build_jar.py", line 58, in <module>
    subprocess.run(command, cwd=args.source, shell=True, check=True)
  File "/home/ubuntu/anaconda3/envs/kuzushiji/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/home/ubuntu/.konduit/konduit-serving/mvnw -Puberjar clean install -Dmaven.test.skip=true -Djavacpp.platform=linux-x86_64-gpu  -Dchip=gpu -Ppython -Ppmml' returned non-zero exit status 1.
```

There is no artifact `org.bytedeco:hdf5:jar:linux-x86_64-gpu:1.10.5-1.5.1`.

Build succeeds in case of without GPU i.e. `--os linux-x86_64` option.

**Comment by ShamsUlAzeem** [comment]
Hmm the `-gpu` suffix shouldn't be there
