### ISSUE TITLE
`konduit init` does not work if whitespace in path 

### ISSUE THREAD

**Issue by philip-khor** [KonduitAI/konduit-serving#118]
```
(base) C:\Users\Skymind AI Berhad>konduit init --os windows-x86_64
Already up to date.
Python 3.7.5
Running command: C:\Users\Skymind AI Berhad\.konduit\konduit-serving\mvnw -Puberjar clean install -Dmaven.test.skip=true -Djavacpp.platform=windows-x86_64  -Dchip=cpu -Ppython -Ppmml
'C:\Users\Skymind' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Users\Skymind AI Berhad\.konduit\konduit-serving\build_jar.py", line 58, in <module>
    subprocess.run(command, cwd=args.source, shell=True, check=True)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'C:\Users\Skymind AI Berhad\.konduit\konduit-serving\mvnw -Puberjar clean install -Dmaven.test.skip=true -Djavacpp.platform=windows-x86_64  -Dchip=cpu -Ppython -Ppmml' returned non-zero exit status 1.
```

**Comment by maxpumperla** [comment]
@maxpumperla the git pull bit runs, but mvnw still fails:

Running command: C:\Users\Skymind AI Berhad\.konduit\konduit-serving\mvnw -Puberjar clean install -Dmaven.test.skip=true -Djavacpp.platform=windows-x86_64 -Dchip=cpu -Ppython -Ppmml
Traceback (most recent call last):
  File "C:\Users\Skymind AI Berhad\.konduit\konduit-serving\build_jar.py", line 88, in <module>
    subprocess.call(command)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application
Same error if build_jar.py is run directly.

complete log: https://gist.github.com/philip-khor/220288bf4e93118b30d95f4d03f53250

**Comment by maxpumperla** [comment]
@philip-khor I transferred your issue comment here and reopened the issue.

as for directly calling `mvnw`, on the command line you have to to the string escaping for the path yourself. your error message says that the second argument, namely `AI`, is not executable.

I don't quite understand why Python does not properly encode your path in the current version on windows. it works for me on linux...

**Comment by maxpumperla** [comment]
@philip-khor can you check again with @ShamsUlAzeem fix?

also, @maxpumperla still talking you yourself, huh?

**Comment by philip-khor** [comment]
latest fix works now, thanks!
