### ISSUE TITLE
NameError: name 'ServingConfig' is not defined

### ISSUE THREAD

**Issue by philip-khor** [KonduitAI/konduit-serving#129]
b247b211d5e2441e781ddc960bfed12dff446890 removes the following line, which imports a number of Konduit classes in the Python SDK such as ServingConfig

https://github.com/KonduitAI/konduit-serving/blob/4b09600e79d2b06b1dae192cf4591d6b103f3bfc/python/konduit/load.py#L1

Serving a [simple YAML from konduit-serving-examples](https://github.com/KonduitAI/konduit-serving-examples/blob/master/yaml/simple.yaml) with the following CLI command returns the following traceback: 

```
(base) philip@philip-HP-ENVY-x360-Convertible-13-ar0xxx:~/konduit-serving-examples$ konduit serve --config yaml/simple.yaml
Traceback (most recent call last):
  File "/home/philip/miniconda3/bin/konduit", line 11, in <module>
    load_entry_point('konduit==0.1.4', 'console_scripts', 'konduit')()
  File "/home/philip/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/philip/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/philip/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/philip/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/philip/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/philip/miniconda3/lib/python3.7/site-packages/konduit-0.1.4-py3.7.egg/cli.py", line 133, in serve
  File "/home/philip/miniconda3/lib/python3.7/site-packages/konduit-0.1.4-py3.7.egg/konduit/load.py", line 124, in server_from_file
NameError: name 'ServingConfig' is not defined
```

**Comment by maxpumperla** [comment]
thanks, will be fixed in #131
