### ISSUE TITLE
Class not found b'ai/konduit/serving/util/SchemaTypeUtils'

### ISSUE THREAD

**Issue by bewithme** [KonduitAI/konduit-serving#147]
I run the command as following step 

1.  python build_jar.py --os linux-x86_64
2. python konduit-serving/python/setup.py install
3. konduit serve --config yaml/simple.yaml

error as bellow when I execute the step 3

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/konduit-0.1.4-py3.7.egg/konduit/inference.py", line 5, in <module>
  File "/opt/anaconda3/lib/python3.7/site-packages/jnius/reflect.py", line 158, in autoclass
    c = find_javaclass(clsname)
  File "jnius/jnius_export_func.pxi", line 25, in jnius.find_javaclass
jnius.JavaException: Class not found b'ai/konduit/serving/util/SchemaTypeUtils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/bin/konduit", line 11, in <module>
    load_entry_point('konduit==0.1.4', 'console_scripts', 'konduit')()
  File "/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/konduit-0.1.4-py3.7.egg/cli.py", line 122, in serve
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/opt/anaconda3/lib/python3.7/site-packages/konduit-0.1.4-py3.7.egg/konduit/__init__.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/opt/anaconda3/lib/python3.7/site-packages/konduit-0.1.4-py3.7.egg/konduit/inference.py", line 12, in <module>
Exception: ("We couldn't initialize the Java classes used by Konduit. Make sure to have a konduit.jar available on your PATH, for instance by setting the environment variable KONDUIT_JAR_PATH to point to such a JAR.\n", JavaException("Class not found b'ai/konduit/serving/util/SchemaTypeUtils'"))

**Comment by bewithme** [comment]
I found the reason,  export KONDUIT_JAR_PATH="~/konduit-serving/konduit.jar" should be change to export KONDUIT_JAR_PATH="your absolute path/konduit.jar"

**Comment by maxpumperla** [comment]
@bewithme few things of note here. the first command you run builds the `konduit.jar` locally in the repo you probably cloned before and then attempts to copy it to `python/tests`. in your second command you then install the Python library, but to initialize the CLI properly you need to run `konduit init --os linux-x86_64` first. That command would create `~/.konduit/konduit-serving/konduit.jar` and make the CLI usable from anywhere in your system (as `konduit-python` will look there first). the `init` command would hence make your first command obsolete. 

after that 3. should work as expected. I should also note that you could also set the `KONDUIT_JAR_PATH` to whatever you like / where your jar is located.

**Comment by maxpumperla** [comment]
@bewithme can we close this then or is there anything else you need right now?

**Comment by bewithme** [comment]
@maxpumperla  yes thank you so much
