### ISSUE TITLE
Unable to instantiate pipeline step from class ai.konduit.serving.pipeline.steps.PythonStepRunner

### ISSUE THREAD

**Issue by bewithme** [KonduitAI/konduit-serving#148]
when I run konduit serve --config yaml/simple.yaml , show error as bellow:

16:20:14.413 [vert.x-worker-thread-0] ERROR a.k.s.c.PipelineRouteDefiner - Failed to initialize. Shutting down.
java.lang.IllegalStateException: Unable to instantiate pipeline step from class ai.konduit.serving.pipeline.steps.PythonStepRunner
	at ai.konduit.serving.pipeline.BasePipelineStep.createRunner(BasePipelineStep.java:311)
	at ai.konduit.serving.executioner.Pipeline.getPipeline(Pipeline.java:65)
	at ai.konduit.serving.executioner.PipelineExecutioner.init(PipelineExecutioner.java:257)
	at ai.konduit.serving.configprovider.PipelineRouteDefiner.defineRoutes(PipelineRouteDefiner.java:479)
	at ai.konduit.serving.verticles.inference.InferenceVerticle.init(InferenceVerticle.java:83)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:553)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.WorkerContext.lambda$wrapTask$0(WorkerContext.java:35)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at ai.konduit.serving.pipeline.BasePipelineStep.createRunner(BasePipelineStep.java:309)
	... 12 common frames omitted
Caused by: java.lang.NullPointerException: No code to run!
	at org.nd4j.base.Preconditions.throwNullPointerEx(Preconditions.java:646)
	at org.nd4j.base.Preconditions.checkNotNull(Preconditions.java:470)
	at ai.konduit.serving.pipeline.steps.PythonStepRunner.<init>(PythonStepRunner.java:111)
	... 17 common frames omitted
16:20:14.413 [vert.x-worker-thread-0] INFO  a.k.s.c.PipelineRouteDefiner - Using metrics registry io.micrometer.prometheus.PrometheusMeterRegistry for inference
16:20:15.438 [vert.x-worker-thread-0] INFO  a.k.s.p.steps.PythonStepRunner - Over riding python path .
16:20:15.438 [vert.x-worker-thread-0] ERROR a.k.s.p.steps.PythonStepRunner - Unable to read code from ../python/simple.py
16:20:15.438 [vert.x-worker-thread-0] INFO  a.k.s.p.steps.PythonStepRunner - Resolving code from ../python/simple.py
16:20:15.438 [vert.x-worker-thread-0] ERROR a.k.s.c.PipelineRouteDefiner - Failed to initialize. Shutting down.
java.lang.IllegalStateException: Unable to instantiate pipeline step from class ai.konduit.serving.pipeline.steps.PythonStepRunner
	at ai.konduit.serving.pipeline.BasePipelineStep.createRunner(BasePipelineStep.java:311)
	at ai.konduit.serving.executioner.Pipeline.getPipeline(Pipeline.java:65)
	at ai.konduit.serving.executioner.PipelineExecutioner.init(PipelineExecutioner.java:257)
	at ai.konduit.serving.configprovider.PipelineRouteDefiner.defineRoutes(PipelineRouteDefiner.java:479)
	at ai.konduit.serving.verticles.inference.InferenceVerticle.init(InferenceVerticle.java:88)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:553)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.WorkerContext.lambda$wrapTask$0(WorkerContext.java:35)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at ai.konduit.serving.pipeline.BasePipelineStep.createRunner(BasePipelineStep.java:309)
	... 12 common frames omitted
Caused by: java.lang.NullPointerException: No code to run!
	at org.nd4j.base.Preconditions.throwNullPointerEx(Preconditions.java:646)
	at org.nd4j.base.Preconditions.checkNotNull(Preconditions.java:470)
	at ai.konduit.serving.pipeline.steps.PythonStepRunner.<init>(PythonStepRunner.java:111)
	... 17 common frames omitted
Dec 09, 2019 4:20:15 PM ai.konduit.serving.configprovider.KonduitServingMain
INFO: Deployed verticle {}
Starting server..

Server has started successfully.

**Comment by bewithme** [comment]
yaml file content as bellow:

serving:
  http_port: 1337
  input_data_format: NUMPY
  output_data_format: NUMPY
  log_timings: True
  extra_start_args: -Xmx8g
steps:
  python_step:
    type: PYTHON
    python_path: .
    python_code_path: ../python/simple.py
    python_inputs:
      first: NDARRAY
    python_outputs:
      second: NDARRAY
client:
    port: 1337

**Comment by philip-khor** [comment]
The location where you run the command matters. Can you please try the following YAML: 
```yaml
serving:
  http_port: 1337
  input_data_format: NUMPY
  output_data_format: NUMPY
  log_timings: True
  extra_start_args: -Xmx8g
steps:
  python_step:
    type: PYTHON
    python_code: |
      import numpy as np
      first += 2
      second = first
    python_inputs:
      first: NDARRAY
    python_outputs:
      second: NDARRAY
client:
    port: 1337
```

**Comment by bewithme** [comment]
@philip-khor  I found the reason , I change python_code_path: ../python/simple.py to absolute  python_code_path and it is work now. so maybe it is not bug .

**Comment by philip-khor** [comment]
@bewithme no problems! 

since you're in the root folder of konduit-serving-examples (my guess), using the relative path `python/simple.py` should work too.
