### ISSUE TITLE
[macOS] incompatible return types error with getpwuid(int)

### ISSUE THREAD

**Issue by kmotohas** [KonduitAI/konduit-serving#159]
When I tried `face_detection_pytorch/run_konduit.py` on macOS Catarlina, the following error was shown.
`konduit init --os macosx-x86_64` itself works fine.

```
...
09:48:42.508 [vert.x-worker-thread-0] INFO  a.k.s.c.PipelineRouteDefiner - Using metrics registry io.micrometer.prometheus.PrometheusMeterRegistry for inference
12 16, 2019 9:48:42 午前 ai.konduit.serving.configprovider.KonduitServingMain
重大: Unable to deploy verticle {}
java.lang.ExceptionInInitializerError
	at oshi.util.platform.mac.SysctlUtil.sysctl(SysctlUtil.java:119)
	at oshi.hardware.platform.mac.MacCentralProcessor.<clinit>(MacCentralProcessor.java:53)
	at oshi.hardware.platform.mac.MacHardwareAbstractionLayer.getProcessor(MacHardwareAbstractionLayer.java:53)
	at oshi.json.hardware.impl.HardwareAbstractionLayerImpl.getProcessor(HardwareAbstractionLayerImpl.java:89)
	at org.deeplearning4j.perf.listener.HardwareMetric.fromSystem(HardwareMetric.java:94)
	at ai.konduit.serving.metrics.NativeMetrics.bindTo(NativeMetrics.java:59)
	at ai.konduit.serving.configprovider.PipelineRouteDefiner.defineRoutes(PipelineRouteDefiner.java:159)
	at ai.konduit.serving.verticles.inference.InferenceVerticle.init(InferenceVerticle.java:83)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:553)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.WorkerContext.lambda$wrapTask$0(WorkerContext.java:35)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: methods with same signature getpwuid(int) but incompatible return types: [class oshi.jna.platform.mac.SystemB$Passwd, class com.sun.jna.platform.mac.SystemB$Passwd]
	at sun.misc.ProxyGenerator.checkReturnTypes(ProxyGenerator.java:712)
	at sun.misc.ProxyGenerator.generateClassFile(ProxyGenerator.java:461)
	at sun.misc.ProxyGenerator.generateProxyClass(ProxyGenerator.java:339)
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:639)
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)
	at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
	at java.lang.reflect.WeakCache.get(WeakCache.java:127)
	at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719)
	at com.sun.jna.Native.loadLibrary(Native.java:648)
	at com.sun.jna.Native.loadLibrary(Native.java:630)
	at oshi.jna.platform.mac.SystemB.<clinit>(SystemB.java:39)
	... 16 more

Starting server.........................

The server wasn't able to start.
```

```
$ java -version
java version "1.8.0_212"
Java(TM) SE Runtime Environment (build 1.8.0_212-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.212-b10, mixed mode)
```

**Comment by saudet** [comment]
Looks like there are conflicting dependencies of JNA somewhere @AlexDBlack

**Comment by maxpumperla** [comment]
@kmotohas do you know when exactly this occurred first? I've certainly never seen this before.

**Comment by kmotohas** [comment]
Sorry I'm not sure. I think that was 1 or 2 weeks ago.

**Comment by agibsonccc** [comment]
I think @saudet is right. I'll make sure to add a dependencyManagement section for jna.

**Comment by ShamsUlAzeem** [comment]
Updating oshi versions would help I think

**Comment by ShamsUlAzeem** [comment]
You can cherry-pick this: https://github.com/KonduitAI/konduit-serving/commit/683b89d34c473a0657c34ba6dbcd97fbe1dbfabd

**Comment by agibsonccc** [comment]
@ShamsUlAzeem @kmotohas please do not use that fix. This needs to be done with proper dependencyManagement.

**Comment by agibsonccc** [comment]
> @ShamsUlAzeem @kmotohas please do not use that fix. This needs to be done with proper dependencyManagement. 1 off verisons should _NEVER_ be used, especially when you're blending a bunch of dependencies. You _NEED_ to use dependencyManagement to prevent transitive dependencies from failing. EIther submit a separate PR or if you're in a hurry I can get it done.

Ok added a fix.
