### ISSUE TITLE
Regex in build_jar.py not compatible with 1.0.0-SNAPSHOT 

### ISSUE THREAD

**Issue by philip-khor** [KonduitAI/konduit-serving#182]
Running `konduit build` on latest master returns 

```
Traceback (most recent call last):
  File "C:\Users\Skymind AI Berhad\.konduit\konduit-serving\build_jar.py", line 100, in <module>
    os.path.join(args.source, args.target),
  File "c:\users\skymind ai berhad\appdata\local\continuum\miniconda3\envs\pytorch\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Skymind AI Berhad\\.konduit\\konduit-serving\\konduit-serving-uberjar\\target\\konduit-serving-uberjar-20190722-bin.jar'
```

The regex here: 
https://github.com/KonduitAI/konduit-serving/blob/f0b829ec13e1fc3f675cfc6dbd85dec26f14defe/build_jar.py#L84-L87

searches through `pom.xml` in the root directory for matches, and later on sets the first element of the list `version` as the version number for the source uberjar's file name: 

https://github.com/KonduitAI/konduit-serving/blob/f0b829ec13e1fc3f675cfc6dbd85dec26f14defe/build_jar.py#L93-L101

However, this regex does not match a version number if there are non-digit characters trailing the version number. 

Additionally, the source file's name no longer ends in <version.number>-bin.jar: on my machine, it's 

> konduit-serving-uberjar-0.1.0-SNAPSHOT-custom-windows-x86_64-cpu.jar

**Comment by philip-khor** [comment]
Fixed in #184
