### ISSUE TITLE
Unsupported DataType : Bool using pythonvariable in PythonConfig

### ISSUE THREAD

**Issue by venkat-nidrive** [KonduitAI/konduit-serving#204]
setting Bool in  pythonvariables  as follows ,
 .pythonInput("inputVar", PythonVariables.Type.BOOL.name())
Getting the below error .

Caused by: java.lang.Exception: Unsupported python input type: Boolean ( PythonUtils.java) 
Caused by: java.lang.Exception: Unsupported python input type: Boolean
	at org.datavec.python.PythonUtils.schemaToPythonVariables(PythonUtils.java:126)
	at org.datavec.python.PythonTransform.setInputSchema(PythonTransform.java:126)

Test Source available in the below fork.
https://github.com/RabertNIDrive/konduit-serving

Branch :  nidrive/pythonpipelinetest

**Comment by venkat-nidrive** [comment]
@farizrahman4u
