### ISSUE TITLE
 Unable to perform json inference due to Cast Exception  (Assign Float value to Int) PythonConfig 

### ISSUE THREAD

**Issue by venkat-nidrive** [KonduitAI/konduit-serving#205]
Assign Float value to Int during Inference using PythonStep.

Config as follows ,
  PythonConfig pythonConfig = PythonConfig.builder()
                .pythonCodePath(pythonCodePath)
                .pythonPath(pythonPath)
                .pythonInput("inputVar", PythonVariables.Type.INT.name())
                .pythonOutput("output", PythonVariables.Type.INT.name())
                .build();

Assigned value as below and inference  : 

        Float floatValue = 100.25f;
        inputJson.put("inputVar", floatValue);

        requestSpecification.body(inputJson.encode().getBytes());
        requestSpecification.header("Content-Type", "application/json");
        String output = requestSpecification.when()
                .expect().statusCode(500)
                .body(not(isEmptyOrNullString()))
                .post("/raw/json").then()
                .extract()
                .body().asString();

Error as follows:
17:14:58.893 [vert.x-worker-thread-2] INFO  a.k.s.e.PipelineExecutioner - Auto converting json object to json array
17:14:58.897 [vert.x-worker-thread-2] INFO  a.k.s.p.h.c.JsonArrayMapConverter - Converting [{"inputVar":25.54}]
17:14:59.290 [vert.x-worker-thread-2] WARN  org.datavec.arrow.ArrowConverter - Unable to set value at row 0
17:14:59.366 [vert.x-worker-thread-2] ERROR a.k.s.c.PipelineRouteDefiner - Unable to perform json inference
java.lang.ClassCastException: org.datavec.api.writable.NullWritable cannot be cast to org.datavec.api.writable.IntWritable
	at org.datavec.python.PythonTransform.getPyInputsFromWritables(PythonTransform.java:239)
	at org.datavec.python.PythonTransform.map(PythonTransform.java:165)
	at org.datavec.local.transforms.transform.LocalTransformFunction.apply(LocalTransformFunction.java:48)
	at org.datavec.local.transforms.transform.LocalTransformFunction.apply(LocalTransformFunction.java:32)
	at org.datavec.local.transforms.LocalTransformExecutor.lambda$execute$3(LocalTransformExecutor.java:340)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)

**Comment by venkat-nidrive** [comment]
@farizrahman4u
