### ISSUE TITLE
'konduit serve' command JSON/YAML validation + shut down if launch fails

### ISSUE THREAD

**Issue by AlexDBlack** [KonduitAI/konduit-serving#384]
I recently (accidentally) did a `konduit serve -c somefile.json`
However this file was a pipeline json file, not an InferenceConfiguration file.

(However, having the ability to do `konduit serve -c model_config.json <args for http server etc>` might nice to have regardless)

The result was an error but the server still "running" in a zombie state: (i.e., I had to manually do `konduit stop <id>`)
```
00:02:23.915 [main] INFO  u.o.l.s.context.SysOutOverSLF4J - Replaced standard System.out and System.err PrintStreams with SLF4JPrintStreams
00:02:23.918 [main] INFO  u.o.l.s.context.SysOutOverSLF4J - Redirected System.out and System.err to SLF4J for this context
00:02:23.918 [main] INFO  a.k.s.c.l.command.KonduitRunCommand - Starting konduit server with an id of 'server'
00:02:24.647 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable - java.lang.NullPointerException
00:02:24.647 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at ai.konduit.serving.vertx.verticle.InferenceVerticle.init(InferenceVerticle.java:52)
00:02:24.647 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:553)
00:02:24.647 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
00:02:24.647 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
00:02:24.647 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
00:02:24.647 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
00:02:24.648 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
00:02:24.648 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
00:02:24.648 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
00:02:24.648 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
00:02:24.648 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at java.lang.Thread.run(Thread.java:748)
Jun 20, 2020 12:02:24 AM io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
SEVERE: Failed in deploying verticle
java.lang.NullPointerException
        at ai.konduit.serving.vertx.verticle.InferenceVerticle.init(InferenceVerticle.java:52)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:553)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by AlexDBlack** [comment]
Similarly, a bad path for a TF model results is a zombie server process:
https://gist.github.com/AlexDBlack/e11e99d1af79f95b5609e7d7ed891827

And listing doesn't work either due to the pid.data file not being written (due to the error)
```
Listing konduit servers...

 #   | ID                             | TYPE       | URL                  | PID     | STATUS
Error occurred while reading server configuration file:
java.io.FileNotFoundException: File 'C:\Users\Alex\.konduit-serving\servers\31520.data' does not exist
        at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:297)
        at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1805)
        at ai.konduit.serving.cli.launcher.command.ListCommand.printServerDetails(ListCommand.java:122)
        at ai.konduit.serving.cli.launcher.command.ListCommand.dumpFoundVertxApplications(ListCommand.java:99)
        at ai.konduit.serving.cli.launcher.command.ListCommand.run(ListCommand.java:72)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:248)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:383)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:346)
        at ai.konduit.serving.cli.launcher.KonduitServingLauncher.main(KonduitServingLauncher.java:63)
 1   | server                         | inference  | waiting...           | 31520   | starting
```
