### ISSUE TITLE
ModelGuesserException: Unable to load model from path (invalid model file or not a known model type)

### ISSUE THREAD

**Issue by zulhusnirahman** [KonduitAI/konduit-serving#456]
I have issues trying to run my text detection model using konduit serving jar and encountered this error.

```
17:47:19.110 [vert.x-worker-thread-0] ERROR a.k.s.model.loader.ModelGuesser - Failure to load keras file
java.lang.RuntimeException: H5Aopen failed
        at org.bytedeco.hdf5.H5Object.openAttribute(Native Method)
        at org.deeplearning4j.nn.modelimport.keras.Hdf5Archive.readAttributeAsFixedLengthString(Hdf5Archive.java:431)
        at ai.konduit.serving.model.loader.ModelGuesser.isKerasComputationGraphFile(ModelGuesser.java:111)
        at ai.konduit.serving.executioner.inference.factory.KerasInferenceExecutionerFactory.create(KerasInferenceExecutionerFactory.java:51)
        at ai.konduit.serving.pipeline.steps.InferenceExecutionerStepRunner.<init>(InferenceExecutionerStepRunner.java:95)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at ai.konduit.serving.pipeline.BasePipelineStep.createRunner(BasePipelineStep.java:393)
        at ai.konduit.serving.executioner.Pipeline.getPipeline(Pipeline.java:65)
        at ai.konduit.serving.executioner.PipelineExecutioner.init(PipelineExecutioner.java:259)
        at ai.konduit.serving.configprovider.PipelineRouteDefiner.defineRoutes(PipelineRouteDefiner.java:674)
        at ai.konduit.serving.verticles.inference.InferenceVerticle.init(InferenceVerticle.java:79)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:553)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
        at io.vertx.core.impl.WorkerContext.lambda$wrapTask$0(WorkerContext.java:35)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
17:47:19.114 [vert.x-worker-thread-0] WARN  a.k.s.model.loader.ModelGuesser - Tried multi layer network
17:47:19.114 [vert.x-worker-thread-0] WARN  a.k.s.model.loader.ModelGuesser - Tried computation graph
17:47:19.118 [vert.x-worker-thread-0] WARN  a.k.s.model.loader.ModelGuesser - Tried multi layer network keras
17:47:19.120 [vert.x-worker-thread-0] ERROR a.k.s.c.PipelineRouteDefiner - Failed to initialize. Shutting down.
java.lang.IllegalStateException: Unable to instantiate pipeline step from class ai.konduit.serving.pipeline.steps.InferenceExecutionerStepRunner
        at ai.konduit.serving.pipeline.BasePipelineStep.createRunner(BasePipelineStep.java:395)
        at ai.konduit.serving.executioner.Pipeline.getPipeline(Pipeline.java:65)
        at ai.konduit.serving.executioner.PipelineExecutioner.init(PipelineExecutioner.java:259)
        at ai.konduit.serving.configprovider.PipelineRouteDefiner.defineRoutes(PipelineRouteDefiner.java:674)
        at ai.konduit.serving.verticles.inference.InferenceVerticle.init(InferenceVerticle.java:79)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:553)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
        at io.vertx.core.impl.WorkerContext.lambda$wrapTask$0(WorkerContext.java:35)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at ai.konduit.serving.pipeline.BasePipelineStep.createRunner(BasePipelineStep.java:393)
        ... 12 common frames omitted
Caused by: java.lang.IllegalStateException: org.deeplearning4j.util.ModelGuesserException: Unable to load model from path C:\Users\zulhu\Desktop\konduit-invoice-processing\workflow\Script\text_detection.h5 (invalid model file or not a known model type)
        at ai.konduit.serving.pipeline.steps.InferenceExecutionerStepRunner.<init>(InferenceExecutionerStepRunner.java:100)
        ... 17 common frames omitted
Caused by: org.deeplearning4j.util.ModelGuesserException: Unable to load model from path C:\Users\zulhu\Desktop\konduit-invoice-processing\workflow\Script\text_detection.h5 (invalid model file or not a known model type)
        at ai.konduit.serving.model.loader.ModelGuesser.loadModelGuess(ModelGuesser.java:332)
        at ai.konduit.serving.model.loader.dl4j.mln.MultiLayerNetworkModelLoader.loadModel(MultiLayerNetworkModelLoader.java:57)
        at ai.konduit.serving.model.loader.dl4j.mln.MultiLayerNetworkModelLoader.loadModel(MultiLayerNetworkModelLoader.java:37)
        at ai.konduit.serving.executioner.inference.MultiLayerNetworkInferenceExecutioner.initialize(MultiLayerNetworkInferenceExecutioner.java:60)
        at ai.konduit.serving.executioner.inference.factory.KerasInferenceExecutionerFactory.create(KerasInferenceExecutionerFactory.java:70)
        at ai.konduit.serving.pipeline.steps.InferenceExecutionerStepRunner.<init>(InferenceExecutionerStepRunner.java:95)
        ... 17 common frames omitted
17:47:19.122 [vert.x-worker-thread-0] INFO  a.k.s.c.PipelineRouteDefiner - Using metrics registry io.micrometer.prometheus.PrometheusMeterRegistry for inference
17:47:20.392 [vert.x-worker-thread-0] ERROR a.k.s.model.loader.ModelGuesser - Failure to load keras file
java.lang.RuntimeException: H5Aopen failed
        at org.bytedeco.hdf5.H5Object.openAttribute(Native Method)
        at org.deeplearning4j.nn.modelimport.keras.Hdf5Archive.readAttributeAsFixedLengthString(Hdf5Archive.java:431)
        at ai.konduit.serving.model.loader.ModelGuesser.isKerasComputationGraphFile(ModelGuesser.java:111)
        at ai.konduit.serving.executioner.inference.factory.KerasInferenceExecutionerFactory.create(KerasInferenceExecutionerFactory.java:51)
        at ai.konduit.serving.pipeline.steps.InferenceExecutionerStepRunner.<init>(InferenceExecutionerStepRunner.java:95)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at ai.konduit.serving.pipeline.BasePipelineStep.createRunner(BasePipelineStep.java:393)
        at ai.konduit.serving.verticles.inference.InferenceVerticle.init(InferenceVerticle.java:88)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:553)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
        at io.vertx.core.impl.WorkerContext.lambda$wrapTask$0(WorkerContext.java:35)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
17:47:20.394 [vert.x-worker-thread-0] WARN  a.k.s.model.loader.ModelGuesser - Tried multi layer network
17:47:20.396 [vert.x-worker-thread-0] WARN  a.k.s.model.loader.ModelGuesser - Tried computation graph
17:47:20.398 [vert.x-worker-thread-0] WARN  a.k.s.model.loader.ModelGuesser - Tried multi layer network keras
Jul 14, 2020 5:47:20 PM ai.konduit.serving.configprovider.KonduitServingMain
SEVERE: Unable to deploy verticle {}
java.lang.IllegalStateException: Unable to instantiate pipeline step from class ai.konduit.serving.pipeline.steps.InferenceExecutionerStepRunner
        at ai.konduit.serving.pipeline.BasePipelineStep.createRunner(BasePipelineStep.java:395)
        at ai.konduit.serving.verticles.inference.InferenceVerticle.init(InferenceVerticle.java:88)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:553)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
        at io.vertx.core.impl.WorkerContext.lambda$wrapTask$0(WorkerContext.java:35)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at ai.konduit.serving.pipeline.BasePipelineStep.createRunner(BasePipelineStep.java:393)
        ... 9 more
Caused by: java.lang.IllegalStateException: org.deeplearning4j.util.ModelGuesserException: Unable to load model from path C:\Users\zulhu\Desktop\konduit-invoice-processing\workflow\Script\text_detection.h5 (invalid model file or not a known model type)
        at ai.konduit.serving.pipeline.steps.InferenceExecutionerStepRunner.<init>(InferenceExecutionerStepRunner.java:100)
        ... 14 more
Caused by: org.deeplearning4j.util.ModelGuesserException: Unable to load model from path C:\Users\zulhu\Desktop\konduit-invoice-processing\workflow\Script\text_detection.h5 (invalid model file or not a known model type)
        at ai.konduit.serving.model.loader.ModelGuesser.loadModelGuess(ModelGuesser.java:332)
        at ai.konduit.serving.model.loader.dl4j.mln.MultiLayerNetworkModelLoader.loadModel(MultiLayerNetworkModelLoader.java:57)
        at ai.konduit.serving.model.loader.dl4j.mln.MultiLayerNetworkModelLoader.loadModel(MultiLayerNetworkModelLoader.java:37)
        at ai.konduit.serving.executioner.inference.MultiLayerNetworkInferenceExecutioner.initialize(MultiLayerNetworkInferenceExecutioner.java:60)
        at ai.konduit.serving.executioner.inference.factory.KerasInferenceExecutionerFactory.create(KerasInferenceExecutionerFactory.java:70)
        at ai.konduit.serving.pipeline.steps.InferenceExecutionerStepRunner.<init>(InferenceExecutionerStepRunner.java:95)
        ... 14 more
```
The model is trained in keras with tensorflow backend (not tf.keras) and was loaded into konduit using the konduit serving jar file.

'java -d64 -cp " + jarPath +  " ai.konduit.serving.configprovider.KonduitServingMain"  + " --configPath " + configPath'

The model can be downloaded from this link. https://drive.google.com/file/d/17Wbe0E6hs9Brz2rCZW1ZYxeQfx5QpESE/view?usp=sharing

The config file can be found here. https://drive.google.com/file/d/1-Bb1wDPEMAjaLajtw3TJPfAdQF0-mFGB/view?usp=sharing

**Comment by agibsonccc** [comment]
HI, this is the underlying error from the debugger:
org.deeplearning4j.nn.modelimport.keras.exceptions.InvalidKerasConfigurationException: Model configuration attribute missing from text_detection.h5 archive.. For more information, see https://deeplearning4j.konduit.ai/keras-import/overview

Do you mind double checking the deeplearning4j model import to verify your model configuration?

**Comment by agibsonccc** [comment]
@zulhusnirahman 
I just tried:
```
from keras.models import load_model
load_model('text_detection.h5')
```

Keras gives me: ValueError: No model found in config file.

I'm not sure how you produced this, but keras itself is saying this is an invalid model, so I'm going to just close this.
