### ISSUE TITLE
Python runner crashes when input type is NDARRAY and output type is STR

### ISSUE THREAD

**Issue by kmotohas** [KonduitAI/konduit-serving#91]
The face detection example fails after its input type is changed from `STR` to `NDARRAY`.
https://github.com/KonduitAI/konduit-serving/blob/kuzushiji/python/examples/face_detection_pytorch/run_konduit.py
https://github.com/KonduitAI/konduit-serving/blob/kuzushiji/python/examples/face_detection_pytorch/detect_image.py

It seems the server assumes types of input and output are same.

```
21:07:57.699 [vert.x-worker-thread-18] ERROR a.k.s.c.PipelineRouteDefiner - Failed to do inference 
java.lang.ClassCastException: org.datavec.api.writable.Text cannot be cast to org.datavec.api.writable.NDArrayWritable
	at ai.konduit.serving.util.SchemaTypeUtils.toArrays(SchemaTypeUtils.java:263)
	at ai.konduit.serving.executioner.Pipeline.doPipelineArrays(Pipeline.java:108)
	at ai.konduit.serving.executioner.PipelineExecutioner.doInference(PipelineExecutioner.java:288)
	at ai.konduit.serving.configprovider.PipelineRouteDefiner.lambda$null$6(PipelineRouteDefiner.java:333)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

Full error log is found here https://gist.github.com/kmotohas/40de09a8009920d7058f95f5c027ff1b

Inference itself works correctly according to this line https://gist.github.com/kmotohas/40de09a8009920d7058f95f5c027ff1b#file-run_konduit-log-L739

**Comment by ShamsUlAzeem** [comment]
@kmotohas You're right. A couple of things that are happening here that makes achieving the output difficult in this case when the output is specified as a STR. When we specify the input type in the client as a `NUMPY` array then the outputs are automatically assumed as arrays because the request is then sent as a multipart request (this the way it is setup for now). Keeping that in mind, when you specify output as STR it internally tried to convert that output into an ndarray even though it should not. 

@maxpumperla @agibsonccc we need to find a way to generalize this behavior even if the request is sent as multipart. This function call tries to convert everything into and NDArrayWritable: https://github.com/KonduitAI/konduit-serving/blob/4f5e01525160719e49057a4b4425a03b6688f325/konduit-serving-api/src/main/java/ai/konduit/serving/util/SchemaTypeUtils.java#L255...

@kmotohas a simple workaround for this is the following: 

In the `detect_image.py` file return the output as `num_boxes = np.array([len(boxes)])` and then in the `run_konduit.py` file, specify the output type as `python_outputs={'num_boxes': 'NDARRAY'}` and serving config as `serving_config = ServingConfig(http_port=1337, input_data_type='NUMPY', output_data_type='JSON', prediction_type="RAW")` after that you'll be able to get the `num_boxes` through `predicted['default']['ndArray']['data'][0]`

**Comment by agibsonccc** [comment]
@ShamsUlAzeem @kmotohas  @maxpumperla if the input type is ndarray and it's multi part, then the assumption it's an ndarray is 
 fine. The output adapter is generally supposed to take care of ndarrays being converted to a particular type of output.

I think the bug you're seeing is different. This happens on the input, not on the output conversion.
The input *should* be an ndarray going in.
The client appears to be serializing it wrong. The client should be serializing things to ndarrays before sending it to the server.

**Comment by maxpumperla** [comment]
@agibsonccc @ShamsUlAzeem I think by default we should think "numpy in, numpy out" for Python users. I'm not saying this issue is not substantial, we need to fix that bug. but the number of output boxes from a model can also just be a numpy scalar and users can convert them to a string afterwards (note that this situation is a leftover artifact of the previous workaround using Strings). 

https://github.com/KonduitAI/konduit-serving/blob/460a5c2c24625d6c25069e1908443eea27af26e4/python/examples/face_detection_pytorch/run_konduit_minimal.py#L11-L25

If you do it like this in #101 you don't need to worry about strings at all. What I want to say is that, to avoid confusion, we should not promote string output types.

**Comment by agibsonccc** [comment]
@ShamsUlAzeem @kmotohas  keep an eye on this: https://github.com/KonduitAI/konduit-serving/pull/111 we will make the validation a bit more obvious to prevent stuff like this. I may modify the python pipeline step as well with the types.
